// Code generated by logcopter-gen; DO NOT EDIT.

package main

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.go-go-os-backend.cmd.go-go-os-backend")
